In [1]:
import numpy as np
a=np.array([1,2,3])

In [2]:
a

array([1, 2, 3])

In [3]:
b = np.array([4,5,6])
b

array([4, 5, 6])

In [4]:
a+b

array([5, 7, 9])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.itemsize

4

In [17]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [18]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [19]:
np.shape(a)

(2, 2)

In [20]:
a+b

array([[ 6,  8],
       [10, 12]])

In [21]:
a-b

array([[-4, -4],
       [-4, -4]])

In [22]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [23]:
a*b

array([[ 5, 12],
       [21, 32]])

In [24]:
a.ravel()

array([1, 2, 3, 4])

In [30]:
a = np.arange(12).reshape(2,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [31]:
a[0]

array([0, 1, 2, 3, 4, 5])

In [32]:
np.hsplit(a,3)

[array([[0, 1],
        [6, 7]]),
 array([[2, 3],
        [8, 9]]),
 array([[ 4,  5],
        [10, 11]])]

In [34]:
b =np.vsplit(a,2)

In [35]:
b[0]

array([[0, 1, 2, 3, 4, 5]])

In [36]:
b[1]

array([[ 6,  7,  8,  9, 10, 11]])

In [37]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
b= a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [40]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [42]:
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [43]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [44]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a[0:2,2]

array([2, 6])

In [46]:
a[2,0:2]

array([8, 9])

In [47]:
a[:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a[:,-1]

array([ 3,  7, 11])

In [49]:
a[-1,:]

array([ 8,  9, 10, 11])

In [53]:
for row in a.flatten():
    print(row)
    

0
1
2
3
4
5
6
7
8
9
10
11


In [57]:
import numpy as np
for row in np.nditer(a,order='C'):
    print (row)

0
1
2
3
4
5
6
7
8
9
10
11


In [58]:
for i in np.nditer(a, order='F'):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


In [69]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
b = np.arange(3).reshape(3,1)
b

array([[0],
       [1],
       [2]])

In [72]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 0
1 0
2 0
3 0
4 1
5 1
6 1
7 1
8 2
9 2
10 2
11 2
